---
- name: Install packages to allow apt to use a repository over HTTPS
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present
    update_cache: yes

# This is not working
# - name: Add Docker’s official GPG key
#   apt_key:
#     url: https://download.docker.com/linux/ubuntu/gpg
#     state: present

- name: Add Docker’s official GPG key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  args:
    warn: no

- name: Set up stable repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lsb_release }} stable
    state: present

- name: Install the latest version of Docker CE and containerd
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes

- name: Create the docker group
  group:
    name: docker
    state: present

- name: Add user to docker group
  user:
    name: '{{ user }}'
    append: yes
    group: docker

- name: Setup docker daemon cgroup driver
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json

- name: Create docker.service.d directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
  notify: Restart docker